#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
        KC_GRAVE,       KC_1,           KC_2,           KC_3,           KC_4,           KC_5,                               KC_6,       KC_7,           KC_8,           KC_9,           KC_0,               KC_MINUS,
        KC_TAB,         KC_Q,           KC_W,           KC_E,           KC_R,           KC_T,                               KC_Y,       KC_U,           KC_I,           KC_O,           KC_P,               KC_EQUAL,
        KC_ESCAPE,      LSFT_T(KC_A),   LCTL_T(KC_S),   LALT_T(KC_D),   LGUI_T(KC_F),   KC_G,                               KC_H,       LGUI_T(KC_J),   LALT_T(KC_K),   LCTL_T(KC_L),   LSFT_T(KC_SCLN),    KC_QUOTE,
        KC_LCTL,        KC_Z,           KC_X,           KC_C,           KC_V,           KC_B,       KC_LBRC,    KC_RBRC,    KC_N,       KC_M,           KC_COMMA,       KC_DOT,         KC_SLASH,           KC_RCTL,
                                        KC_LALT,        KC_LSFT,        MO(1),          KC_BSPC,                            KC_SPACE,   MO(2),          KC_LEFT,        KC_RIGHT
    ),

    [1] = LAYOUT(
        KC_TRNS,        KC_TRNS,              KC_TRNS,        KC_TRNS,        KC_TRNS,        KC_TRNS,                            KC_TRNS,        KC_TRNS,        KC_TRNS,        KC_TRNS,        KC_TRNS,        KC_TRNS,
        KC_F1,          KC_F2,                KC_UP,          LSFT(KC_MINUS), KC_MINUS,       KC_F6,                             KC_F7,          KC_F8,          KC_F9,          KC_F10,         KC_F11,         KC_F12,
        KC_LCTL,        LSFT(KC_LBRC),        KC_LBRC,        LSFT(KC_9),     LSFT(KC_QUOTE), KC_TRNS,                           KC_LEFT,        KC_QUOTE,       LSFT(KC_0),     KC_RBRC,        LSFT(KC_RBRC),  LSFT(KC_GRAVE),
        KC_TRNS,        KC_TRNS,              KC_TRNS,        KC_TRNS,        KC_TRNS,        KC_TRNS,    KC_TRNS,    KC_TRNS,   KC_NO,          LSFT(KC_MINUS), LSFT(KC_EQUAL), LSFT(KC_LBRC),  LSFT(KC_RBRC),  LSFT(KC_BSLS),
                                              KC_TRNS,        KC_TRNS,        KC_TRNS,        KC_TRNS,                           KC_TRNS,        MO(3),          KC_TRNS,        KC_TRNS
    ),

    [2] = LAYOUT(
        KC_TRNS,        KC_TRNS,        KC_TRNS,        KC_TRNS,        KC_TRNS,        KC_TRNS,                            KC_TRNS,        KC_TRNS,        KC_TRNS,        KC_TRNS,        KC_TRNS,        KC_TRNS,
        KC_GRAVE,       KC_1,           KC_2,           KC_3,           KC_4,           KC_5,                              KC_6,           KC_7,           KC_8,           KC_9,           KC_0,           KC_TRNS,
        KC_F1,          KC_F2,          KC_F3,          KC_F4,          KC_F5,          KC_F6,                             KC_LEFT,        KC_DOWN,        KC_UP,          KC_RIGHT,       KC_NO,          KC_NO,
        KC_F7,          KC_F8,          KC_VOLD,        KC_F10,         KC_F11,         KC_F12,     KC_TRNS,    KC_TRNS,   LSFT(KC_EQUAL), KC_MINUS,       KC_VOLD,        KC_VOLU,        KC_RBRC,        KC_BSLS,
                                        KC_TRNS,        KC_TRNS,        MO(3),          KC_TRNS,                           KC_TRNS,        KC_TRNS,        KC_TRNS,        KC_TRNS
    ),

    [3] = LAYOUT(
        KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,                              KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,
        KC_NO,          KC_NO,          KC_UP,          KC_NO,          KC_NO,          KC_NO,                              KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,
        KC_NO,          KC_LEFT,        KC_DOWN,        KC_RIGHT,       KC_NO,          KC_NO,                              KC_NO,          KC_NO,          RGB_TOG,        RGB_HUI,        RGB_SAI,        RGB_VAI,
        KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,       KC_NO,      KC_NO,     KC_NO,          KC_NO,          RGB_MOD,        RGB_HUD,        RGB_SAD,        RGB_VAD,
                                        KC_TRNS,        KC_TRNS,        KC_TRNS,        KC_TRNS,                           KC_TRNS,        KC_TRNS,        KC_TRNS,        KC_TRNS
    )
};

// Define combos
enum combo_events {
  JK_ENTER,
  BF_LPAREN
};

const uint16_t PROGMEM jk_enter_combo[] = {LGUI_T(KC_J), LALT_T(KC_K), COMBO_END};
const uint16_t PROGMEM bf_paren_combo[] = {KC_BSPC, KC_F, COMBO_END};

combo_t key_combos[] = {
    COMBO(jk_enter_combo, KC_ENT),
    COMBO(bf_paren_combo, KC_LPRN)  // Changed to KC_LPRN instead of LSFT(KC_9)
};

#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

